server:
   port: 8085

spring:
  jpa:
     show-sql: true
     #hibernate:
      #ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/db_curs-000189_alcancias?createDatabaseIfNotExist=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123

# Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port:8085}

# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always

# Azure Service Bus
azure:
 service:
  connectionString: Endpoint=sb://nsalcanciadzg.servicebus.windows.net/;SharedAccessKeyName=keasdasd;SharedAccessKey=C0W0pct3ipDT8JsJC+5DBxIYeHIo4Ousy+ASbE99eho=
  queueName: queuegtdz